package Exception_Handling;

public class Try_Catch {

	public static void main(String[] args) {
		try {
int t1= 1/1;
System.out.println(t1);
	}
	catch(java.lang.ArithmeticException y1)
	{
		System.out.println("roohi");
	}

}
}
